//  Mandar isso pro DB
module.exports = {
    DRAW_FIRST_DUNGEON: 0,
    DRAW_SECOND_DUNGEON: 1,
    FIGHT_MONSTER: 2,
    FIGHT_MONSTER_LOOSING: 3,
    FIGHT_MONSTER_WINNING: 4,
    FIGHT_MONSTER_ASK_HELP: 5,
    FIGHT_MONSTER_HELP_RESPONSE: 6,
    FIGHT_MONSTER_INTERFERE: 7
};
